CREATE TABLE HangDienThoai (
    Hang_ID NVARCHAR(255) PRIMARY KEY,
    TenHang NVARCHAR(255) NOT NULL
);

CREATE TABLE DienThoai (
    DienThoai_ID NVARCHAR(255) PRIMARY KEY,
    Hang_ID NVARCHAR(255),
    TenDienThoai NVARCHAR(255) NOT NULL,
    GiaBan DECIMAL(18, 2) NOT NULL,
    FOREIGN KEY (Hang_ID) REFERENCES HangDienThoai(Hang_ID)
);

CREATE TABLE USERR (
    User_ID NVARCHAR(255) PRIMARY KEY,
    Ten NVARCHAR(255) NOT NULL,
    ChucVu NVARCHAR(255) NOT NULL,
    CaLamViec NVARCHAR(255) NOT NULL,
    TaiKhoan NVARCHAR(255) NOT NULL,
    MatKhau NVARCHAR(255) NOT NULL
);

CREATE TABLE DonHang (
    DonHang_ID NVARCHAR(255) PRIMARY KEY,
    DienThoai_ID NVARCHAR(255),
    Hang_ID NVARCHAR(255),
    User_ID NVARCHAR(255),
    TenDienThoai NVARCHAR(255) NOT NULL,
    SoLuong INT NOT NULL,
    TongTien DECIMAL(18, 2) NOT NULL,
    Ngay DATE NOT NULL,
    FOREIGN KEY (DienThoai_ID) REFERENCES DienThoai(DienThoai_ID),
    FOREIGN KEY (Hang_ID) REFERENCES HangDienThoai(Hang_ID),
    FOREIGN KEY (User_ID) REFERENCES USERR(User_ID)
);