/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QLCHDTAndroid;
import com.sun.jdi.connect.spi.Connection;
import java.awt.print.PrinterException;
import java.math.BigDecimal;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author THANH
 */
public class AdminDonHang extends javax.swing.JFrame {
           java.sql.Connection con = null; 
PreparedStatement pst = null; 
ResultSet rs = null;

    /**
     * Creates new form Admin
     */
    public AdminDonHang() {
        initComponents();
        this.setLocationRelativeTo(null);
        showDataDonHang();
        
        
    }
         public void  showDataDonHang(){  
    try {
        con = DriverManager.getConnection("jdbc:sqlserver://LAPTOP-MPLEJDGS\\SQLEXPRESS:1433;databaseName=QLCHDTAndroid;encrypt=true;trustServerCertificate=true", "sa", "sa"); 
        pst = con.prepareStatement("SELECT * FROM DonHang"); 
        rs = pst.executeQuery(); 
        
        DefaultTableModel model = new DefaultTableModel(); 
        tableDonHang.setModel(model); 
        
       model.addColumn("Mã đơn hàng_ID");
        model.addColumn("Mã điện thoại_ID");
          model.addColumn("Mã hãng ID");
            model.addColumn("Mã nhân viên tiếp thị");
            model.addColumn(" Tên điện thoại");
            model.addColumn(" Ngày bán");
            model.addColumn("Số lượng");
            model.addColumn(" Tổng tiền ");
        
        while(rs.next()) { 
            model.addRow(new Object[] {rs.getString("DonHang_ID"),rs.getString("DienThoai_ID"),rs.getString("Hang_ID"),rs.getString("User_ID"),rs.getString("TenDienThoai"),rs.getString("Ngay"), rs.getString("so_luong"),rs.getString("tong_tien")});
        }   
    } catch (SQLException ex) {
        System.out.println("Hệ Thống chạy lỗi!!!");
    }   
} 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnAdmin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        butDonHang = new javax.swing.JButton();
        butNhanVien = new javax.swing.JButton();
        butThongKe = new javax.swing.JButton();
        butHangHoa = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnrf = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfMaDonHang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfMaDienThoai = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableDonHang = new javax.swing.JTable();
        butXoaDonHang = new javax.swing.JButton();
        butHuyDonHang = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tfMaHang = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfMaNhanVien = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tfTenDienThoai = new javax.swing.JTextField();
        tfSoLuong = new javax.swing.JTextField();
        tfTongTien = new javax.swing.JTextField();
        tfNgayBan = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jpnAdmin.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLCHDTAndroid/admin.png"))); // NOI18N

        butDonHang.setBackground(new java.awt.Color(255, 102, 102));
        butDonHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        butDonHang.setForeground(new java.awt.Color(255, 255, 255));
        butDonHang.setText("ĐƠN HÀNG");
        butDonHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butDonHangActionPerformed(evt);
            }
        });

        butNhanVien.setBackground(new java.awt.Color(58, 196, 195));
        butNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        butNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        butNhanVien.setText("NGƯỜI DÙNG");
        butNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butNhanVienMouseClicked(evt);
            }
        });
        butNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butNhanVienActionPerformed(evt);
            }
        });

        butThongKe.setBackground(new java.awt.Color(58, 196, 195));
        butThongKe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        butThongKe.setForeground(new java.awt.Color(255, 255, 255));
        butThongKe.setText("THỐNG KÊ");
        butThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butThongKeActionPerformed(evt);
            }
        });

        butHangHoa.setBackground(new java.awt.Color(58, 196, 195));
        butHangHoa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        butHangHoa.setForeground(new java.awt.Color(255, 255, 255));
        butHangHoa.setText("HÀNG HÓA");
        butHangHoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butHangHoaMouseClicked(evt);
            }
        });
        butHangHoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butHangHoaActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton1.setText("THOÁT");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        btnrf.setBackground(new java.awt.Color(58, 196, 195));
        btnrf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnrf.setForeground(new java.awt.Color(255, 255, 255));
        btnrf.setText("REFRESH");
        btnrf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnAdminLayout = new javax.swing.GroupLayout(jpnAdmin);
        jpnAdmin.setLayout(jpnAdminLayout);
        jpnAdminLayout.setHorizontalGroup(
            jpnAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpnAdminLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jpnAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(butThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(butNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(butDonHang, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(butHangHoa, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(btnrf, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnAdminLayout.setVerticalGroup(
            jpnAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnAdminLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(butHangHoa, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(butDonHang, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(butNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(butThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnrf, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel2.setText("DANH SÁCH ĐƠN HÀNG");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Mã đơn hàng :");

        tfMaDonHang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Mã Hãng :");

        tfMaDienThoai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfMaDienThoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMaDienThoaiActionPerformed(evt);
            }
        });

        tableDonHang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tableDonHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableDonHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDonHangMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableDonHang);

        butXoaDonHang.setBackground(new java.awt.Color(58, 196, 195));
        butXoaDonHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        butXoaDonHang.setForeground(new java.awt.Color(255, 255, 255));
        butXoaDonHang.setText("Xóa");
        butXoaDonHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butXoaDonHangActionPerformed(evt);
            }
        });

        butHuyDonHang.setBackground(new java.awt.Color(58, 196, 195));
        butHuyDonHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        butHuyDonHang.setForeground(new java.awt.Color(255, 255, 255));
        butHuyDonHang.setText("Hủy");
        butHuyDonHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butHuyDonHangActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Mã nhân viên :");

        tfMaHang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfMaHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMaHangActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Mã điện thoại :");

        tfMaNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfMaNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMaNhanVienActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Tên điện thoại :");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Số lượng :");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Tổng tiền :");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Ngày bán :");

        tfTenDienThoai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        tfSoLuong.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        tfTongTien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        tfNgayBan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 845, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(86, 86, 86)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(78, 78, 78)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfMaDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfMaDonHang, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfMaHang, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(20, 20, 20))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12))
                                        .addGap(51, 51, 51))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(274, 274, 274)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tfTongTien, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                                .addComponent(tfSoLuong, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfTenDienThoai, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(tfNgayBan, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(butXoaDonHang, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(butHuyDonHang, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMaDonHang, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTenDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMaDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNgayBan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMaHang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butXoaDonHang)
                    .addComponent(butHuyDonHang))
                .addGap(17, 17, 17))
        );

        jTabbedPane1.addTab("Đơn hàng", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butDonHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butDonHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butDonHangActionPerformed

    private void tfMaDienThoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMaDienThoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMaDienThoaiActionPerformed

    private void tfMaHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMaHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMaHangActionPerformed

    private void tfMaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMaNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMaNhanVienActionPerformed

    private void butHangHoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butHangHoaMouseClicked
this.dispose();
        try {
            new AdminHangHoa().setVisible(true);        // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(AdminDonHang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_butHangHoaMouseClicked

    private void butNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butNhanVienActionPerformed

    private void butNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butNhanVienMouseClicked
this.dispose();
        try {
            new User().setVisible(true);        // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(AdminDonHang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_butNhanVienMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void tableDonHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDonHangMouseClicked
    {
            int selectedRow = tableDonHang.getSelectedRow();   
        if(tableDonHang.getValueAt(selectedRow, 0) == null ){ 
            tfMaDonHang.setText(""); 
            tfMaDienThoai.setText(""); 
            tfMaHang.setText(""); 
             tfMaNhanVien.setText(""); 
              tfTenDienThoai.setText("");
               tfNgayBan.setText("");
               tfSoLuong.setText("");
               tfTongTien.setText("");
           
              
            
        } else { 
        tfMaDonHang.setText(tableDonHang.getValueAt(selectedRow, 0).toString());  
          tfMaDienThoai.setText(tableDonHang.getValueAt(selectedRow, 1).toString()); 
         tfMaHang.setText(tableDonHang.getValueAt(selectedRow, 2).toString());  
          tfMaNhanVien.setText(tableDonHang.getValueAt(selectedRow, 3).toString());  
           tfTenDienThoai.setText(tableDonHang.getValueAt(selectedRow, 4).toString());  
            tfNgayBan.setText(tableDonHang.getValueAt(selectedRow, 5).toString());  
             tfSoLuong.setText(tableDonHang.getValueAt(selectedRow, 6).toString());  
              tfTongTien.setText(tableDonHang.getValueAt(selectedRow, 7).toString());  
        }
      }
    }//GEN-LAST:event_tableDonHangMouseClicked

    private void butHuyDonHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butHuyDonHangActionPerformed
              tfMaDonHang.setText("");
               tfMaDienThoai.setText("");
                tfMaHang.setText("");
                 tfMaNhanVien.setText("");
                  tfTenDienThoai.setText("");
                   tfNgayBan.setText("");
                    tfSoLuong.setText("");
                     tfTongTien.setText("");
    }//GEN-LAST:event_butHuyDonHangActionPerformed

    private void butXoaDonHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butXoaDonHangActionPerformed
         try { 
        con = DriverManager.getConnection("jdbc:sqlserver://LAPTOP-MPLEJDGS\\SQLEXPRESS:1433;databaseName=QLCHDTAndroid;encrypt=true;trustServerCertificate=true", "sa", "sa"); 
        pst = con.prepareStatement("DELETE DonHang WHERE DonHang_ID = ?");   
         if(tfMaDonHang.getText().isEmpty() || tfMaDienThoai.getText().isEmpty()|| tfMaHang.getText().isEmpty()|| tfMaNhanVien.getText().isEmpty() || tfTenDienThoai.getText().isEmpty() || tfNgayBan.getText().isEmpty() || tfSoLuong.getText().isEmpty() || tfTongTien.getText().isEmpty())
        { 
            JOptionPane.showMessageDialog(null, "Chưa nhập dữ liệu", "Thông báo", JOptionPane.ERROR_MESSAGE);    
        } else { 
        pst.setString(1, tfMaDonHang.getText().toString()); 
        pst.executeUpdate();  
        JOptionPane.showMessageDialog(null, "Đã xóa", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        showDataDonHang();            
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Đã  có lỗi xãy ra", "Thông báo", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_butXoaDonHangActionPerformed

    private void butThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butThongKeActionPerformed
        this.dispose();
         new AdThongKe().setVisible(true);
    }//GEN-LAST:event_butThongKeActionPerformed

    private void btnrfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrfActionPerformed
          this.dispose();
          new AdminDonHang().setVisible(true);
    }//GEN-LAST:event_btnrfActionPerformed

    private void butHangHoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butHangHoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butHangHoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDonHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnrf;
    private javax.swing.JButton butDonHang;
    private javax.swing.JButton butHangHoa;
    private javax.swing.JButton butHuyDonHang;
    private javax.swing.JButton butNhanVien;
    private javax.swing.JButton butThongKe;
    private javax.swing.JButton butXoaDonHang;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jpnAdmin;
    private javax.swing.JTable tableDonHang;
    private javax.swing.JTextField tfMaDienThoai;
    private javax.swing.JTextField tfMaDonHang;
    private javax.swing.JTextField tfMaHang;
    private javax.swing.JTextField tfMaNhanVien;
    private javax.swing.JTextField tfNgayBan;
    private javax.swing.JTextField tfSoLuong;
    private javax.swing.JTextField tfTenDienThoai;
    private javax.swing.JTextField tfTongTien;
    // End of variables declaration//GEN-END:variables
}
