/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QLCHDTAndroid;
import com.sun.jdi.connect.spi.Connection;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.ImageIcon;
import java.sql.DriverManager;

import java.sql.ResultSet;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import org.mindrot.jbcrypt.BCrypt;




/**
 *
 * @author THANH
 */
public class Login extends javax.swing.JFrame {
       java.sql.Connection con = null; 
PreparedStatement pst = null; 
ResultSet rs = null;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
          this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jtfDangNhap = new javax.swing.JTextField();
        txtpass = new javax.swing.JPasswordField();
        buttonDangNhap = new javax.swing.JButton();
        cbb = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hello Tôi là Mèo Đen");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtfDangNhap.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        jtfDangNhap.setForeground(new java.awt.Color(0, 51, 51));
        jtfDangNhap.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtfDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDangNhapActionPerformed(evt);
            }
        });
        panel.add(jtfDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 220, 36));

        txtpass.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassActionPerformed(evt);
            }
        });
        panel.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 220, 42));

        buttonDangNhap.setBackground(new java.awt.Color(255, 102, 102));
        buttonDangNhap.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        buttonDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        buttonDangNhap.setText("Login");
        buttonDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDangNhapActionPerformed(evt);
            }
        });
        panel.add(buttonDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 110, 43));

        cbb.setFont(new java.awt.Font("SimSun", 1, 14)); // NOI18N
        cbb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhân viên", "Admin" }));
        cbb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbActionPerformed(evt);
            }
        });
        panel.add(cbb, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 148, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLCHDTAndroid/user-regular.png"))); // NOI18N
        panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 50, 48));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLCHDTAndroid/key-solid_1.png"))); // NOI18N
        panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, -1, 73));

        jLabel4.setFont(new java.awt.Font("SimSun", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ANDROID PHONE STORE");
        panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        jLabel6.setFont(new java.awt.Font("SimSun", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Coppy right by @Vi Huu Thanh");
        panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 740, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLCHDTAndroid/panellogin.png"))); // NOI18N
        panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 930, 550));

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDangNhapActionPerformed

       try { 
        con = DriverManager.getConnection("jdbc:sqlserver://LAPTOP-MPLEJDGS\\SQLEXPRESS:1433;databaseName=QLCHDTAndroid;encrypt=true;trustServerCertificate=true", "sa", "sa"); 
        boolean checkFault = true; 
        String type = cbb.getSelectedItem().toString(); 

        // Lấy mật khẩu băm từ cơ sở dữ liệu
        pst = con.prepareStatement("SELECT * FROM USERR WHERE TaiKhoan = ?");
        pst.setString(1, jtfDangNhap.getText()); // Tài khoản

        rs = pst.executeQuery();   

        if (rs.next()) {  
            // Lấy mật khẩu băm từ cơ sở dữ liệu
            String hashedPassword = rs.getString("MatKhau");

            // Kiểm tra mật khẩu
            if (BCrypt.checkpw(txtpass.getText(), hashedPassword)) {
                // Đóng cửa sổ đăng nhập
                this.dispose(); 

                if (type.contains("Nhân viên")) {
                    // Lấy giá trị từ ResultSet
                    String ten = rs.getNString("Ten");
                    String user_ID = rs.getNString("User_ID");

                    // Tạo một đối tượng TrangBanHang với các giá trị trên
                    TrangBanHang trangBanHang = new TrangBanHang(ten, user_ID);

                    // Hiển thị đối tượng duy nhất
                    trangBanHang.setVisible(true);

                } else if (type.contains("Admin")) {
                    new AdminHangHoa().setVisible(true);
                }

                checkFault = false;
            }
        }    

        if(checkFault) { 
            JOptionPane.showMessageDialog(null, "Sai mật khẩu hoặc tài khoản", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    } catch (SQLException ex) {
        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    }

            

    }//GEN-LAST:event_buttonDangNhapActionPerformed

    private void jtfDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDangNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDangNhapActionPerformed

    private void txtpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassActionPerformed

    private void cbbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDangNhap;
    private javax.swing.JComboBox<String> cbb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jtfDangNhap;
    private javax.swing.JPanel panel;
    private javax.swing.JPasswordField txtpass;
    // End of variables declaration//GEN-END:variables
}
