/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QLCHDTAndroid;
import ChatFunction.ChatClientController;
import ChatFunction.ChatClientView;
import com.sun.jdi.connect.spi.Connection;
import java.awt.print.PrinterException;
import java.math.BigDecimal;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author THANH
 */
public class TrangBanHang extends javax.swing.JFrame {
       java.sql.Connection con = null; 
PreparedStatement pst = null; 
ResultSet rs = null;
    

    /**
     * Creates new form NhanVien
     */
    public TrangBanHang() {
        initComponents();
        this.setLocationRelativeTo(null);     
        showDataDienThoai();
         getDate();
        
        
    }
    
    
     public TrangBanHang(String Ten, String User_ID) {  
        initComponents(); 
        this.setLocationRelativeTo(null);
        showDataDienThoai(); 
        getDate();
        tfTenNhanVien.setText(Ten);    
        txtMaNV.setText(User_ID);   
        
    }
     
     
     
    
     public void getDate() { 
        Date date = new Date();  
        SimpleDateFormat form = new SimpleDateFormat("yyyy-MM-dd");  
        String today = String.valueOf(form.format(date));
        tfNgayBan.setText(today.toString());
    }
       
    
      public void  showDataDienThoai(){  
    try {
        con = DriverManager.getConnection("jdbc:sqlserver://LAPTOP-MPLEJDGS\\SQLEXPRESS:1433;databaseName=QLCHDTAndroid;encrypt=true;trustServerCertificate=true", "sa", "sa"); 
        pst = con.prepareStatement("SELECT * FROM DienThoai"); 
        rs = pst.executeQuery(); 
        
        DefaultTableModel model = new DefaultTableModel(); 
        tblDT.setModel(model); 
        
       model.addColumn("Mã Điện Thoại_ID");
        model.addColumn("Mã Hãng_ID");
          model.addColumn("Tên Điện Thoại");
            model.addColumn("Đơn Giá");
        
        while(rs.next()) { 
            model.addRow(new Object[] {rs.getString("DienThoai_ID"),rs.getString("Hang_ID"),rs.getString("TenDienThoai"),rs.getString("GiaBan")});
        }   
    } catch (SQLException ex) {
        System.out.println("Hệ Thống chạy lỗi!!!");
    }   
} 
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfTenNhanVien = new javax.swing.JLabel();
        tfXoaBill1 = new javax.swing.JButton();
        txtMaNV = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tfXoaBill4 = new javax.swing.JButton();
        pnNhanVienBanHang = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfNgayBan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfMaDienThoaiBan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfTenDienThoaiBan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfSoLuongBan = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfDonGiaBan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDT = new javax.swing.JTable();
        butXuatBill = new javax.swing.JButton();
        butThemBill = new javax.swing.JButton();
        tfXoaBill = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        butTotal = new javax.swing.JButton();
        txtTotal = new javax.swing.JLabel();
        txtMaDonHang = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        BillText = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        txtMaHangID = new javax.swing.JTextField();
        tfXoaBill2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        tfSoLuongBan1 = new javax.swing.JTextField();
        tfXoaBill3 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(58, 196, 195));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 48)); // NOI18N
        jLabel1.setText("MOBILE PHONE STORE");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("Tên Nhân Viên : ");

        tfTenNhanVien.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N

        tfXoaBill1.setBackground(new java.awt.Color(255, 102, 102));
        tfXoaBill1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        tfXoaBill1.setText("Thoát");
        tfXoaBill1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfXoaBill1MouseClicked(evt);
            }
        });
        tfXoaBill1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfXoaBill1ActionPerformed(evt);
            }
        });

        txtMaNV.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel15.setText("Mã nhân viên :");

        tfXoaBill4.setBackground(new java.awt.Color(255, 102, 102));
        tfXoaBill4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        tfXoaBill4.setText("Chat");
        tfXoaBill4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfXoaBill4MouseClicked(evt);
            }
        });
        tfXoaBill4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfXoaBill4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfXoaBill4, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(tfXoaBill1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(139, 139, 139))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfTenNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(31, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))))
                .addGap(35, 35, 35))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(tfXoaBill1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfXoaBill4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnNhanVienBanHang.setBackground(new java.awt.Color(255, 255, 255));
        pnNhanVienBanHang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setText("NGÀY");
        pnNhanVienBanHang.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 47, 53, -1));

        tfNgayBan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pnNhanVienBanHang.add(tfNgayBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 76, 100, 35));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setText("MÃ ĐIỆN THOẠI");
        pnNhanVienBanHang.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 47, -1, -1));

        tfMaDienThoaiBan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pnNhanVienBanHang.add(tfMaDienThoaiBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 76, 90, 35));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setText("TÊN ĐIỆN THOẠI");
        pnNhanVienBanHang.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 47, 124, -1));

        tfTenDienThoaiBan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pnNhanVienBanHang.add(tfTenDienThoaiBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 76, 196, 35));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel7.setText("SỐ LƯỢNG");
        pnNhanVienBanHang.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(899, 47, -1, -1));

        tfSoLuongBan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pnNhanVienBanHang.add(tfSoLuongBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(879, 76, 94, 35));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel9.setText("TỔNG TIỀN :");
        pnNhanVienBanHang.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1208, 47, 111, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel10.setText("ĐƠN GIÁ");
        pnNhanVienBanHang.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 47, 74, -1));

        tfDonGiaBan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfDonGiaBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDonGiaBanActionPerformed(evt);
            }
        });
        pnNhanVienBanHang.add(tfDonGiaBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 76, 133, 35));

        tblDT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tblDT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDTMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDT);

        pnNhanVienBanHang.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 218, 545, 308));

        butXuatBill.setBackground(new java.awt.Color(58, 196, 195));
        butXuatBill.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        butXuatBill.setForeground(new java.awt.Color(255, 255, 255));
        butXuatBill.setText("IN/XUẤT BILL");
        butXuatBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butXuatBillActionPerformed(evt);
            }
        });
        pnNhanVienBanHang.add(butXuatBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 490, -1, 36));

        butThemBill.setBackground(new java.awt.Color(58, 196, 195));
        butThemBill.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        butThemBill.setForeground(new java.awt.Color(255, 255, 255));
        butThemBill.setText("THÊM BILL");
        butThemBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butThemBillActionPerformed(evt);
            }
        });
        pnNhanVienBanHang.add(butThemBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 490, 138, 36));

        tfXoaBill.setBackground(new java.awt.Color(58, 196, 195));
        tfXoaBill.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tfXoaBill.setForeground(new java.awt.Color(255, 255, 255));
        tfXoaBill.setText("XÓA");
        tfXoaBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfXoaBillActionPerformed(evt);
            }
        });
        pnNhanVienBanHang.add(tfXoaBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 490, 138, 36));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel11.setText("Danh sách điện thoại :");
        pnNhanVienBanHang.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 177, 176, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel12.setText("Bill :");
        pnNhanVienBanHang.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 135, 36, -1));

        butTotal.setBackground(new java.awt.Color(58, 196, 195));
        butTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        butTotal.setForeground(new java.awt.Color(255, 255, 255));
        butTotal.setText("TỔNG TIỀN");
        butTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butTotalMouseClicked(evt);
            }
        });
        butTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butTotalActionPerformed(evt);
            }
        });
        pnNhanVienBanHang.add(butTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1009, 73, 138, 36));

        txtTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTotal.setText("...");
        txtTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnNhanVienBanHang.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1181, 74, 138, 36));

        txtMaDonHang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtMaDonHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaDonHangActionPerformed(evt);
            }
        });
        pnNhanVienBanHang.add(txtMaDonHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 76, 112, 35));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel8.setText("MÃ ĐƠN HÀNG");
        pnNhanVienBanHang.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 47, 124, -1));

        BillText.setColumns(20);
        BillText.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        BillText.setRows(5);
        jScrollPane2.setViewportView(BillText);

        pnNhanVienBanHang.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 135, 677, 349));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel13.setText("MÃ HÃNG_ID");
        pnNhanVienBanHang.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 47, 106, -1));

        txtMaHangID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pnNhanVienBanHang.add(txtMaHangID, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 76, 106, 35));

        tfXoaBill2.setBackground(new java.awt.Color(255, 102, 102));
        tfXoaBill2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tfXoaBill2.setForeground(new java.awt.Color(255, 255, 255));
        tfXoaBill2.setText("HỦY");
        tfXoaBill2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfXoaBill2MouseClicked(evt);
            }
        });
        tfXoaBill2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfXoaBill2ActionPerformed(evt);
            }
        });
        pnNhanVienBanHang.add(tfXoaBill2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1009, 117, 138, 36));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel14.setText("Tìm điện thoại :");
        pnNhanVienBanHang.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(984, 177, -1, -1));
        pnNhanVienBanHang.add(tfSoLuongBan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 171, 135, 35));

        tfXoaBill3.setBackground(new java.awt.Color(58, 196, 195));
        tfXoaBill3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tfXoaBill3.setForeground(new java.awt.Color(255, 255, 255));
        tfXoaBill3.setText("Tìm");
        tfXoaBill3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfXoaBill3MouseClicked(evt);
            }
        });
        tfXoaBill3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfXoaBill3ActionPerformed(evt);
            }
        });
        pnNhanVienBanHang.add(tfXoaBill3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1251, 170, 83, 35));

        jLabel17.setBackground(new java.awt.Color(58, 196, 195));
        jLabel17.setFont(new java.awt.Font("SimSun", 3, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(58, 196, 195));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Coppy right by @Vi Huu Thanh");
        pnNhanVienBanHang.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 740, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnNhanVienBanHang, javax.swing.GroupLayout.DEFAULT_SIZE, 1350, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnNhanVienBanHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfXoaBill1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfXoaBill1MouseClicked
     this.dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_tfXoaBill1MouseClicked

    private void tfXoaBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfXoaBillActionPerformed
    BillText.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_tfXoaBillActionPerformed

    private void butTotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butTotalMouseClicked
//       int Dongia = Integer.valueOf(tfDonGiaBan.getText());
//       int SoLuong = Integer.valueOf(tfSoLuongBan.getText());
//       int Total = Dongia * SoLuong;
//        String TongTien = String.valueOf(Total);
//        txtTotal.setText(TongTien);
    }//GEN-LAST:event_butTotalMouseClicked

    private void tblDTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDTMouseClicked
           {
            int selectedRow = tblDT.getSelectedRow();   
        if(tblDT.getValueAt(selectedRow, 0) == null ){ 
            tfMaDienThoaiBan.setText(""); 
            txtMaHangID.setText(""); 
            tfTenDienThoaiBan.setText(""); 
             tfDonGiaBan.setText(""); 
           
              
            
        } else { 
        tfMaDienThoaiBan.setText(tblDT.getValueAt(selectedRow, 0).toString());  
          txtMaHangID.setText(tblDT.getValueAt(selectedRow, 1).toString()); 
         tfTenDienThoaiBan.setText(tblDT.getValueAt(selectedRow, 2).toString());  
          tfDonGiaBan.setText(tblDT.getValueAt(selectedRow, 3).toString());  
        }
      }
    }//GEN-LAST:event_tblDTMouseClicked

    private void tfDonGiaBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDonGiaBanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDonGiaBanActionPerformed

    private void butTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butTotalActionPerformed
     
double Dongia = Double.valueOf(tfDonGiaBan.getText());
double SoLuong = Double.valueOf(tfSoLuongBan.getText());
double Total = Dongia * SoLuong;

// Sử dụng DecimalFormat để định dạng số lượng với hai chữ số thập phân
DecimalFormat decimalFormat = new DecimalFormat("0.00");
String TongTien = decimalFormat.format(Total);

txtTotal.setText(TongTien);
    }//GEN-LAST:event_butTotalActionPerformed

    private void butThemBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butThemBillActionPerformed
if (tfNgayBan.getText().isEmpty() || txtMaDonHang.getText().isEmpty()|| txtMaHangID.getText().isEmpty()|| tfMaDienThoaiBan.getText().isEmpty()|| tfTenDienThoaiBan.getText().isEmpty()|| tfSoLuongBan.getText().isEmpty()|| tfDonGiaBan.getText().isEmpty())
{
     JOptionPane.showMessageDialog(null, "Chưa nhập đủ dữ liệu để thêm BILL", "Thông báo", JOptionPane.ERROR_MESSAGE);
}
    else    try {
        con = DriverManager.getConnection("jdbc:sqlserver://LAPTOP-MPLEJDGS\\SQLEXPRESS:1433;databaseName=QLCHDTAndroid;encrypt=true;trustServerCertificate=true", "sa", "sa"); 
      pst = con.prepareStatement("INSERT INTO DonHang VALUES (?, ?, ?, ?, ?, ?, ?, ?)");
      
    pst.setString(1, txtMaDonHang.getText().toString());
pst.setString(2, tfMaDienThoaiBan.getText().toString());
pst.setString(3, txtMaHangID.getText().toString());
 pst.setString(4, txtMaNV.getText().toString());
pst.setString(5, tfTenDienThoaiBan.getText().toString());
pst.setString(6, tfNgayBan.getText().toString());
pst.setString(7, tfSoLuongBan.getText().toString());
pst.setString(8, txtTotal.getText().toString());
     
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Đã thêm vào Bill", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
      
        String billText = "=============== ANDROID PHONE STORE ===============\n"; 
        billText += "Ngày: " + tfNgayBan.getText().toString() + "\n";
        billText += "Mã đơn hàng_ID :" + txtMaDonHang.getText().toString() + "\n";
         billText += "Mã hãng_ID :" + txtMaHangID.getText().toString() + "\n";
        billText += "Mã điện thoại_ID :" + tfMaDienThoaiBan.getText().toString() + "\n";
        billText += "Tên điện thoại : " + tfTenDienThoaiBan.getText().toString() + "\n";
        billText += "Số lượng : " + tfSoLuongBan.getText().toString() + "\n";
        
        billText += "Tổng tiền : " + txtTotal.getText().toString() + "\n";
        billText += "===================================================\n";
        billText += "======  COPPY RIGHT BY @Vi Hữu Thành  ============\n";
        BillText.setText(billText);  
    } catch (SQLException ex) {
        Logger.getLogger(TrangBanHang.class.getName()).log(Level.SEVERE, null, ex);
    }        // TODO add your handling code here:
    }//GEN-LAST:event_butThemBillActionPerformed

    private void butXuatBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butXuatBillActionPerformed
       try {
        BillText.print();
    } catch (PrinterException ex) {
        Logger.getLogger(TrangBanHang.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_butXuatBillActionPerformed

    private void tfXoaBill2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfXoaBill2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tfXoaBill2MouseClicked

    private void tfXoaBill2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfXoaBill2ActionPerformed
   tfNgayBan.setText("");
     txtMaDonHang.setText("");
       txtMaHangID.setText("");
         tfMaDienThoaiBan.setText("");
           tfTenDienThoaiBan.setText("");
             tfSoLuongBan.setText("");
               txtTotal.setText("");
               tfDonGiaBan.setText("");
             
    }//GEN-LAST:event_tfXoaBill2ActionPerformed

    private void tfXoaBill3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfXoaBill3MouseClicked
       try {
    con = DriverManager.getConnection("jdbc:sqlserver://LAPTOP-MPLEJDGS\\SQLEXPRESS:1433;databaseName=QLCHDTAndroid;encrypt=true;trustServerCertificate=true", "sa", "sa"); 
    pst = con.prepareStatement("SELECT * FROM DienThoai WHERE TenDienThoai LIKE ?");
    pst.setString(1, "%" + tfSoLuongBan1.getText().toString() + "%"); // Sử dụng LIKE để tìm kiếm theo mẫu
    
    rs = pst.executeQuery(); 
    
    DefaultTableModel model = new DefaultTableModel(); 
    tblDT.setModel(model); 
    
    model.addColumn("Mã Điện Thoại_ID");
    model.addColumn("Mã Hãng_ID");
    model.addColumn("Tên Điện Thoại");
    model.addColumn("Đơn Giá");
    
    while(rs.next()) { 
        model.addRow(new Object[] {rs.getString("DienThoai_ID"), rs.getString("Hang_ID"), rs.getString("TenDienThoai"), rs.getString("GiaBan")});
    }   
} catch (SQLException ex) {
    ex.printStackTrace();
    JOptionPane.showMessageDialog(null, "Đã có lỗi xãy ra", "Thông báo", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_tfXoaBill3MouseClicked

    private void tfXoaBill3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfXoaBill3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfXoaBill3ActionPerformed

    private void txtMaDonHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaDonHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaDonHangActionPerformed

    private void tfXoaBill1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfXoaBill1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfXoaBill1ActionPerformed

    private void tfXoaBill4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfXoaBill4MouseClicked
   
    }//GEN-LAST:event_tfXoaBill4MouseClicked

    private void tfXoaBill4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfXoaBill4ActionPerformed
ChatClientController controller = new ChatClientController();
    ChatClientView chatClientView = new ChatClientView(controller);
    controller.setView(chatClientView);
    chatClientView.setVisible(true);
    }//GEN-LAST:event_tfXoaBill4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangBanHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea BillText;
    private javax.swing.JButton butThemBill;
    private javax.swing.JButton butTotal;
    private javax.swing.JButton butXuatBill;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnNhanVienBanHang;
    private javax.swing.JTable tblDT;
    private javax.swing.JTextField tfDonGiaBan;
    private javax.swing.JTextField tfMaDienThoaiBan;
    private javax.swing.JTextField tfNgayBan;
    private javax.swing.JTextField tfSoLuongBan;
    private javax.swing.JTextField tfSoLuongBan1;
    private javax.swing.JTextField tfTenDienThoaiBan;
    private javax.swing.JLabel tfTenNhanVien;
    private javax.swing.JButton tfXoaBill;
    private javax.swing.JButton tfXoaBill1;
    private javax.swing.JButton tfXoaBill2;
    private javax.swing.JButton tfXoaBill3;
    private javax.swing.JButton tfXoaBill4;
    private javax.swing.JTextField txtMaDonHang;
    private javax.swing.JTextField txtMaHangID;
    private javax.swing.JLabel txtMaNV;
    private javax.swing.JLabel txtTotal;
    // End of variables declaration//GEN-END:variables
}
